apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
data:
  httpd-vhosts.conf: "<VirtualHost *:8000>\n    DocumentRoot \"/usr/share/httpd/noindex\"\n
    \   ServerName localhost\n    <IfModule mod_proxy_ajp.c>\n      ProxyRequests
    Off\n      ProxyTimeout 300\n      ProxyPreserveHost On\n      ProxyVia On\n\n
    \     <Proxy balancer://grafanaHome>\n        BalancerMember http://grafana-svc
    route=route1\n        ProxySet lbmethod=bybusyness\n      </Proxy>\n      <Location
    /grafana>\n        Order allow,deny\n        Allow from all\n        ProxyPass
    balancer://grafanaHome stickysession=JSESSIONID\n      </Location>\n\n      <Proxy
    balancer://mqhome>\n        BalancerMember http://rabbitmq-svc route=route1\n
    \       ProxySet lbmethod=bybusyness\n      </Proxy>\n      <Location /mq>\n        Order
    allow,deny\n        Allow from all\n        ProxyPass balancer://mqHome stickysession=JSESSIONID\n
    \     </Location>\n\n\n      <Proxy balancer://neo4jHome>\n        BalancerMember
    http://neo4j-svc/browser route=route1\n        ProxySet lbmethod=bybusyness\n
    \     </Proxy>\n      <Location /neo4j>\n        Order allow,deny\n        Allow
    from all\n        ProxyPass balancer://neo4jHome stickysession=JSESSIONID\n      </Location>\n\n
    \     <Proxy balancer://OneDevOpsHome>\n        BalancerMember http://ui-svc/app
    route=route1\n        ProxySet lbmethod=bybusyness\n      </Proxy>\n      <Location
    /app>\n        Order allow,deny\n        Allow from all\n        ProxyPass balancer://OneDevOpsHome
    stickysession=JSESSIONID\n      </Location>\n\n \t  <Proxy balancer://webhookHome>\n\t\tBalancerMember
    http://webhook-svc route=route1\n\t\tProxySet lbmethod=bybusyness\n\t  </Proxy>
    \t  \n\t  <Location /webhook>\n\t\tOrder allow,deny\n\t\tAllow from all\n\t\tProxyPass
    balancer://webhookHome stickysession=JSESSIONID\n\t  </Location>\n      ProxyPass
    \"/PlatformService/\"  \"http://ui-svc/PlatformService/\"\n      ProxyPass \"/google/\"
    \ \"http://ui-svc\"\n    </IfModule>\n</VirtualHost>\n"
  httpd.conf: |2-

    ServerRoot "/etc/httpd"

    Listen  *:8000

    Include conf.modules.d/*.conf

    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
    LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
    LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
    LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule actions_module modules/mod_actions.so
    LoadModule allowmethods_module modules/mod_allowmethods.so
    LoadModule include_module modules/mod_include.so
    LoadModule info_module modules/mod_info.so
    LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
    LoadModule negotiation_module modules/mod_negotiation.so
    LoadModule proxy_connect_module modules/mod_proxy_connect.so
    LoadModule proxy_ftp_module modules/mod_proxy_ftp.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule rewrite_module modules/mod_rewrite.so
    LoadModule socache_shmcb_module modules/mod_socache_shmcb.so

    ServerName localhost:8000

    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    DocumentRoot "/var/www/html"

    <Directory "/var/www">
        AllowOverride None
        # Allow open access:
        Require all granted
    </Directory>

    # Further relax access to the default document root:
    <Directory "/var/www/html">

        Options Indexes FollowSymLinks

        AllowOverride None

        Require all granted
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
        Require all denied
    </Files>

    ErrorLog "logs/error_log"

    LogLevel warn

    <IfModule log_config_module>

        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common

        <IfModule logio_module>
          # You need to enable mod_logio.c to use %I and %O
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>

        CustomLog "logs/access_log" combined
    </IfModule>

    <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
    </IfModule>

    <Directory "/var/www/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>

    <IfModule mime_module>
        TypesConfig /etc/mime.types
        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
        AddType text/html .shtml
        AddOutputFilter INCLUDES .shtml
    </IfModule>

    AddDefaultCharset UTF-8

    <IfModule mime_magic_module>
        MIMEMagicFile conf/magic
    </IfModule>

    #EnableMMAP off
    EnableSendfile on

    IncludeOptional conf.d/*.conf

    # Virtual hosts
    Include conf.d/httpd-vhosts.conf
