apiVersion: v1
kind: Service
metadata:
  name: webhook-svc
  namespace: insights
  labels:
    app: webhook
spec:
  type: ClusterIP
  selector:
    app: webhook
  ports:
  - port: 8981
    targetPort: 8981
