apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: insights
  labels:
    app: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: mansong/platformwebhook:7.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 8981
        env:
          - name: JAVA_OPTS
            value: "-Xmx1024M -Xms500M"
      restartPolicy: Always