apiVersion: v1
kind: ConfigMap
metadata:
  name: uiconfig
data:
  uiConfig.json: |
    {
        "showInsightsTab": false,
        "showOptionsPanel": false,
        "showBusinessMapping": true,
        "agentsOsList": {
                "Windows": "windows",
                "RHEL/CentOS": "linux",
                "Ubuntu":"Ubuntu"
        }
    }
